name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timout-minutes: 10

    steps:
    - name: Check out code
    - uses: actions/checkout@4

    - name: Set up Go
    - uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"
    
    - name: Build app
      run: bash scripts/buildprod.sh
